### ISSUE TITLE
cant spawn live text

### ISSUE THREAD

**Issue by caspervanneck** [EmreTr1/LiveTexts#11]
@EmreTr1

**Comment by EmreTr1** [comment]
I' am opening new branch for 0.16 beta

**Comment by caspervanneck** [comment]
@EmreTr1 can i be memeber to help you

**Comment by EmreTr1** [comment]
Ok

**Comment by caspervanneck** [comment]
and plz fix the /lt addtext comand if i create one it dont show up @EmreTr1

**Comment by EmreTr1** [comment]
Ok
