### ISSUE TITLE
Here's the problem 

### ISSUE THREAD

**Issue by GamingGapple** [EmreTr1/LiveTexts#14]
When I do /lt addtext
05.11 05:07:58 [Server] Server thread/CRITICAL Error: "Call to a member function spawnToAll() on null" (EXCEPTION) in "/phar_LiveTexts-master_ePed7VODbhs8tjx.phar/src/LiveTexts/LiveTexts" at line 114
05.11 05:07:58 [Server] Server thread/CRITICAL Unhandled exception executing command 'lt addtext test' in lt: Call to a member function spawnToAll() on null

When I do /lt add Welcome
05.11 05:10:10 [Server] Server thread/CRITICAL Error: "Call to a member function getNested() on null" (EXCEPTION) in "/phar_LiveTexts-master_ePed7VODbhs8tjx.phar/src/LiveTexts/LiveTexts" at line 157
05.11 05:10:10 [Server] Server thread/CRITICAL Unhandled exception executing command 'lt add Welcome' in lt: Call to a member function getNested() on null

**Comment by caspervanneck** [comment]
@GamingGapple we know about the erors

**Comment by caspervanneck** [comment]
its Fixt i tink
