### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by MagicPandaDev** [EmreTr1/LiveTexts#17]
![img_0644](https://cloud.githubusercontent.com/assets/23283168/20265093/ef290900-aa23-11e6-828f-6f3cb9f843b5.PNG)
I got it working just trying to fix it being visible and the little string thing. Lol that guys does not know what he is doing

**Comment by caspervanneck** [comment]
@MagicPandaDev

**Comment by GamingGapple** [comment]
Lol

**Comment by EmreTr1** [comment]
I am working on Mcpe Software server(Dogger) 
Dogger is a Featured and Advanced Server 

- Support 0.17.1
- Support ResourcePacks
  - TexturePacks +
  -  BehaviourPacks -
  - Add-ons -
- Fast Chunk uploading and sending
- Fast Thread pool
- Walking, Fithging and Flying Mobs(with new Mob.php)
- Enabled Secret Mobs(Wither Egg, Tnt egg, etc.)
- New Mobs

TODO:
 - Fix 0.15 world bug on 0.16+
 - Fix Data Flag bugs

**Comment by EmreTr1** [comment]
@MagicPandaDev LiveTexts not working on 0.16+ because PM Entity data flag tyoes are buggy.
