### ISSUE TITLE
collors dont work

### ISSUE THREAD

**Issue by TiesGamesNL** [EmreTr1/LiveTexts#19]
help when i use collor the texts dont display :(

**Comment by GamingGapple** [comment]
Are you doing addtext or just add (file)

**Comment by caspervanneck** [comment]
@TiesGamesNL werkt voor mij wel

welke teke gebruik je

**Comment by TiesGamesNL** [comment]
oh nvm i found a fix
use: Â§

**Comment by EmreTr1** [comment]
The NetBeansIDE  text bug :d jjss
