### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by ApexDevelops** [EmreTr1/LiveTexts#21]
07.01 16:19:16 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to EmreTr1\Text::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\generic\GenericChunk given, called in phar:///jar/pocketmine/pmmp/1.0/PocketMine-MP.phar/src/pocketmine/entity/Entity__64bit.php on line 514" (EXCEPTION) in "/phar_Test_yECd51qiHnDn3xK.phar/src/EmreTr1/Text" at line 23
07.01 16:19:16 [Server] Server thread/CRITICAL Unhandled exception executing command 'lt addtext Hi' in lt: Argument 1 passed to EmreTr1\Text::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\generic\GenericChunk given, called in phar:///jar/pocketmine/pmmp/1.0/PocketMine-MP.phar/src/pocketmine/entity/Entity__64bit.php on line 514

**Comment by EmreTr1** [comment]
This bug because of PocketMine-MP 1.0 new chunk system.
Ok. I fixing now :)

**Comment by EmreTr1** [comment]
Bug fixed now. Thanks for bug report! 👍
