### ISSUE TITLE
error occurs when running /lt addtext and or /lt add <Welcome.yml>

### ISSUE THREAD

**Issue by ItzWalla** [EmreTr1/LiveTexts#22]
![img_3434](https://cloud.githubusercontent.com/assets/20291307/21958787/01ff31e0-da6b-11e6-80b6-d5a2a594cc18.PNG)

**Comment by XFizzer** [comment]
That's tesseracts problem it's works perfectly fine on elywing and pocketmine

**Comment by ItzWalla** [comment]
Ok, i just stopped using Elywing recently but thanks for the help! @XFizzer

**Comment by ItzWalla** [comment]
Nope, it still makes an error
![img_3436](https://cloud.githubusercontent.com/assets/20291307/21959086/4b01f048-da71-11e6-9ce2-7ddebca18b0d.PNG)

**Comment by XFizzer** [comment]
Then use pocketmine, elywing worked when 1.0.0 first came out

**Comment by EmreTr1** [comment]
This LiveTexts support mcpe1.0
