### ISSUE TITLE
critical

### ISSUE THREAD

**Issue by mote166** [EmreTr1/LiveTexts#27]
this happened when i updated from elywing to tesseract . when i was using elywing the plugins worked just fine but when i updated to tesseract and tried to add a text this it says an error has occurred or something like that and heres what the console says:

CRITICAL> Unhandled exception executing command 'lt addtext hi' in lt: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /plugins/LiveTexts-1.4-dev/src/EmreTr1/LiveTexts.php on line 197 17.03 13:50:12 [Server] INFO [Tesseract] [10:50:12] CRITICAL> TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /plugins/LiveTexts-1.4-dev/src/EmreTr1/LiveTexts.php on line 197" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 632 

* i tried the stabil branch and the 1.4dev branch . it gives the same issue

**Comment by EmreTr1** [comment]
You must update tesseract to last version

**Comment by EmreTr1** [comment]
Support 1.0.4
