### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by PluginBOXone** [EmreTr1/LiveTexts#29]
When i make /lt addtext ..... comes a error in the console! I dont know the entire sentence but I can remember: something with the entity and the chunk .... (Sry for bad english '-' I am german)

**Comment by caspervanneck** [comment]
@PluginBOXone  https://github.com/GalacticSoftware/Galactic-LiveTexts

**Comment by caspervanneck** [comment]
Here is a patch

**Comment by EmreTr1** [comment]
Fixed on Soft brach
