### ISSUE TITLE
Notice?

### ISSUE THREAD

**Issue by bulutsun** [EmreTr1/LiveTexts#30]
Notice: Undefined property: pocketmine\nbt\tag\CompoundTag::$CustomName in phar://C:/Users/Administrator/Desktop/TurkMCPE Network Geli▒tirme Sunucusu 34/plugins/LiveTexts.phar/src/EmreTr1/Text.php on line 27 

How to fix?

**Comment by EmreTr1** [comment]
Fixed on Soft Branch
