### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by XDqrkneZ** [EmreTr1/LiveTexts#35]
Crashdump:

PocketMine-MP Crash Dump Fri Jun 30 14:01:37 MDT 2017

Error: Class pocketmine\network\protocol\AddEntityPacket not found
File: src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 			if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 				$name::onClassLoaded();
[138] 			}
[139] 			
[140] 			$this->classes[] = $name;
[141] 
[142] 			return true;
[143] 		}elseif($this->getParent() === null){
[144] 			throw new ClassNotFoundException("Class $name not found");
[145] 		}
[146] 
[147] 		return false;
[148] 	}
[149] 
[150] 	/**
[151] 	 * Returns the path for the class, if any
[152] 	 *
[153] 	 * @param string $name
[154] 	 *

Backtrace:
#0 (): BaseClassLoader->loadClass(string pocketmine\network\protocol\AddEntityPacket)
#1 LiveTexts-Soft/src/EmreTr1/Text(42): spl_autoload_call(string pocketmine\network\protocol\AddEntityPacket)
#2 src/pocketmine/Player(914): EmreTr1\Text->spawnTo(pocketmine\Player object)
#3 src/pocketmine/Player(833): pocketmine\Player->doFirstSpawn()
#4 src/pocketmine/level/Level(2440): pocketmine\Player->sendChunk(integer -21, integer -97, pocketmine\network\mcpe\protocol\BatchPacket object)
#5 src/pocketmine/level/format/io/ChunkRequestTask(92): pocketmine\level\Level->chunkRequestCallback(integer -21, integer -97, pocketmine\network\mcpe\protocol\BatchPacket object)
#6 src/pocketmine/scheduler/AsyncPool(160): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#7 src/pocketmine/scheduler/ServerScheduler(341): pocketmine\scheduler\AsyncPool->collectTasks()
#8 src/pocketmine/Server(2437): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 5974)
#9 src/pocketmine/Server(2205): pocketmine\Server->tick()
#10 src/pocketmine/Server(2084): pocketmine\Server->tickProcessor()
#11 src/pocketmine/Server(1666): pocketmine\Server->start()
#12 src/pocketmine/PocketMine(505): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/multicraft/jar/pocketmine/pmmp/1.1.0/PocketMine-MP.phar/, string /home/multicraft/servers/server6215/, string /home/multicraft/servers/server6215/plugins/)
#13 /home/multicraft/jar/pocketmine/pmmp/1.1.0/PocketMine-MP.phar(9): include(string phar:///home/multicraft/jar/pocketmine/pmmp/1.1.0/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA6]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mc28.vgmc.us 2.6.32-696.3.2.el6.x86_64 #1 SMP Tue Jun 20 01:26:55 UTC 2017 x86_64
PHP Version: 7.0.19
Zend version: 3.0.0
OS : Linux, linux

**Comment by EmreTr1** [comment]
This plugin working on GenisysPro,Tesseract etc.
Not support Pocketminr-MP
if you are using Pocketmine-MP,
change 'use pocketmine\network\protocol\AddEntityPacket' to 'use pocketmine\network\mcpe\protocol\AddEntityPacket
